spring:
  config:
    activate:
      on-profile: local
    import: 'aws-parameterstore:'
  datasource:
    url: jdbc:mysql://localhost:3306/ifutsalu
    username: ${db-username}
    password: ${db-password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: ifutsalu


