spring:
  config:
    activate:
      on-profile: prd
    import: 'aws-parameterstore:'
  datasource:
    url: ${dev-jdbc-url}
    username: ${db-username}
    password: ${db-password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: ifutsalu


